# Generated by Django 2.2.18 on 2021-02-08 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('idade', models.IntegerField(verbose_name='Idade')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('apelido', models.CharField(blank=True, max_length=50, verbose_name='Apelido')),
                ('observacao', models.TextField(blank=True, max_length=150, verbose_name='Observação')),
            ],
        ),
    ]
